name: precompile

on:
  push:
    tags:
      - "v*"

jobs:
  precompile:
    runs-on: ubuntu-latest
    steps:
      - name: Clone NCNN
        run: |
          git clone --branch=${GITHUB_REF##*/v} https://github.com/Tencent/ncnn.git
          cd ncnn
          git submodule update --init
      - name: Get system deps
        run: |
          sudo apt install build-essential git cmake libprotobuf-dev protobuf-compiler libvulkan-dev vulkan-utils libopencv-dev

      - name: Get vulkan sdk
        run: |
          wget https://sdk.lunarg.com/sdk/download/1.2.189.0/linux/vulkansdk-linux-x86_64-1.2.189.0.tar.gz?Human=true -O vulkansdk-linux-x86_64-1.2.189.0.tar.gz
          tar -xf vulkansdk-linux-x86_64-1.2.189.0.tar.gz
          export VULKAN_SDK=$(pwd)/1.2.189.0/x86_64
      - name: Compile
        run: |
          cd ncnn
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DNCNN_VULKAN=ON -DNCNN_BUILD_EXAMPLES=ON ..
          make -j$(nproc)
          make install
      - name: Create tarball
        run: |
          cd ncnn/build/install
          tar czf ncnn_${GITHUB_REF##*/v}_x86_64-linux-gnu.tar.gz .
      - uses: softprops/action-gh-release@v1
        with:
          files: ncnn/build/install/*.tar.gz
